package view;

import webcontentmanager.WebContentManagerFactory;
import database.DAOImpl;
import javax.swing.Action;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mateusz Gołosz
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    private WindowManager downloadWindowManager;
    public MainView() {
        initComponents();
        downloadWindowManager = WebContentManagerFactory.getInstance().getWindowManager();
        downloadWindowManager.setCreateAlbumFolder(CreateAlbumFolderCheck);
        downloadWindowManager.setCustomLocation(RadioCustom);
        downloadWindowManager.setDefaultLocation(RadioDefault);
        downloadWindowManager.setSaveOriginalFormat(OriginalFormatCheck);
        downloadWindowManager.setFolderLocation(SelectedFolderField);
        MyLogger.init(Logger);
        
    }
    
    public JCheckBox getCreateAlbumFolderCheck() {
        return CreateAlbumFolderCheck;
    }

    public JCheckBox getOriginalFormatCheck() {
        return OriginalFormatCheck;
    }

    public JRadioButton getRadioCustom() {
        return RadioCustom;
    }

    public JRadioButton getRadioDefault() {
        return RadioDefault;
    }

    public JTextField getSelectedFolderField() {
        return SelectedFolderField;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleTextField = new javax.swing.JTextField();
        ArtistTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        TitleLablel = new javax.swing.JLabel();
        ArtistLabel = new javax.swing.JLabel();
        ResultsScrollPane = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        DownloadLabel = new javax.swing.JLabel();
        DownloadScrollPane = new javax.swing.JScrollPane();
        DownloadTable = new javax.swing.JTable();
        downloadAllField = new javax.swing.JTextField();
        downloadAllButton = new javax.swing.JButton();
        SelectFolderButton = new javax.swing.JButton();
        SelectedFolderField = new javax.swing.JTextField();
        RadioDefault = new javax.swing.JRadioButton();
        RadioCustom = new javax.swing.JRadioButton();
        OriginalFormatCheck = new javax.swing.JCheckBox();
        CreateAlbumFolderCheck = new javax.swing.JCheckBox();
        LogLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Logger = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MenuSettings = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
        });

        TitleLablel.setText("Title");

        ArtistLabel.setText("Artist (optional)");

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Result", "Source", "Download"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ResultsScrollPane.setViewportView(SearchTable);
        if (SearchTable.getColumnModel().getColumnCount() > 0) {
            SearchTable.getColumnModel().getColumn(0).setMinWidth(300);
            SearchTable.getColumnModel().getColumn(0).setPreferredWidth(300);
        }

        DownloadLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DownloadLabel.setText("Download");

        DownloadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Progress", "File", "Source", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DownloadScrollPane.setViewportView(DownloadTable);

        downloadAllButton.setText("Download All");
        downloadAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadAllButtonMouseClicked(evt);
            }
        });

        SelectFolderButton.setText("Select folder");
        SelectFolderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectFolderButtonMouseClicked(evt);
            }
        });

        SelectedFolderField.setEditable(false);

        buttonGroup1.add(RadioDefault);
        RadioDefault.setSelected(true);
        RadioDefault.setText("Default location");

        buttonGroup1.add(RadioCustom);
        RadioCustom.setText("Custom location");

        OriginalFormatCheck.setText("Save original format");

        CreateAlbumFolderCheck.setText("Create artist/album folders");

        LogLabel.setText("Logger");

        Logger.setEditable(false);
        Logger.setColumns(20);
        Logger.setRows(5);
        jScrollPane1.setViewportView(Logger);

        FileMenu.setText("File");

        MenuSettings.setText("Settings");
        FileMenu.add(MenuSettings);

        jMenuBar1.add(FileMenu);

        EditMenu.setText("Edit");
        jMenuBar1.add(EditMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(downloadAllField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(downloadAllButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TitleLablel))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ArtistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SearchButton))
                                .addComponent(ArtistLabel)))
                        .addComponent(ResultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SelectedFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectFolderButton)
                                .addGap(74, 447, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CreateAlbumFolderCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(OriginalFormatCheck))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(RadioDefault)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(RadioCustom))
                                        .addComponent(DownloadScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(DownloadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogLabel)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLablel)
                    .addComponent(ArtistLabel))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(ArtistTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DownloadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DownloadScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                        .addComponent(ResultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioDefault)
                    .addComponent(RadioCustom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downloadAllField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadAllButton)
                    .addComponent(SelectFolderButton)
                    .addComponent(SelectedFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OriginalFormatCheck)
                    .addComponent(CreateAlbumFolderCheck))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked
        WebContentManagerFactory.getInstance().getWindowManager().populateSearchTable(TitleTextField.getText(), ArtistTextField, SearchTable, DownloadTable);
    }//GEN-LAST:event_SearchButtonMouseClicked

    private void downloadAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadAllButtonMouseClicked
        /*String location;
        if (RadioCustom.isSelected()) {
            location = SelectedFolderField.getText() + "\\";
        } else {
            location = System.getProperty("user.home") + "\\Downloads\\";
        }*/
        WebContentManagerFactory.getInstance().getWindowManager().downloadAll(downloadAllField.getText(), DownloadTable);
    }//GEN-LAST:event_downloadAllButtonMouseClicked

    private void SelectFolderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectFolderButtonMouseClicked
        WebContentManagerFactory.getInstance().getWindowManager().chooseFolder(SelectedFolderField);
    }//GEN-LAST:event_SelectFolderButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtistLabel;
    private javax.swing.JTextField ArtistTextField;
    private javax.swing.JCheckBox CreateAlbumFolderCheck;
    private javax.swing.JLabel DownloadLabel;
    private javax.swing.JScrollPane DownloadScrollPane;
    private javax.swing.JTable DownloadTable;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel LogLabel;
    private static javax.swing.JTextArea Logger;
    private javax.swing.JMenuItem MenuSettings;
    private javax.swing.JCheckBox OriginalFormatCheck;
    private javax.swing.JRadioButton RadioCustom;
    private javax.swing.JRadioButton RadioDefault;
    private javax.swing.JScrollPane ResultsScrollPane;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable SearchTable;
    private javax.swing.JButton SelectFolderButton;
    private javax.swing.JTextField SelectedFolderField;
    private javax.swing.JLabel TitleLablel;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton downloadAllButton;
    private javax.swing.JTextField downloadAllField;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
